language: java
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -i -S
after_success:
  - ./gradlew uploadJars -S
env:
  global:
  - secure: P422YTy/U4jKEpjZukXTqj3Ms/CqOrJC7f7Uk1IziNkq5D1Y6tXQs+Olq52v0rhLorgquV+gF1J6vlymepzEJz+xs8/bZ437YHIVMCcrA7oVc/b/jjKxubfzwzR1Z0ZOdnZLQrEbY0ZR5oeuXwvhk9CtMZRg1/r5GLA5GV4YL58=
  - secure: A9e8GsyseDNNwXWHbEYa7RmEqO9v3nKVKZA5aDIUYCLjcZBSckFR5X9fDXd1pFnxTasQlFbU3UPR63C5Lm81lSVGrKXA8lLGH5JTAgVcvBcvUvvahYLkXXJYSatBF2p6EfhZWw1eqfZInvDmRcyz4wy4mLK2ZKZjpwYqQGEALrY=
  - secure: gVbfaw5FUcoR4GrpBfZK5145gkog2lsxp+t6+hBk8XVxfYMKr59/oUN0V6OI9S/5kJ/XODLH2+JoYsSBYB2S1VRVsowCmQTnap6cLJHfI1BrL8jfxrJwxqaxt2zKR+Dwl9FSxP83Z8SeICt3csGNLlF2MWawlWLO8hwRso2oqj0=
  - secure: P/mL4W0zH2aGxsRgPZ9AvTfOinsLiXp4h/WPkv6r74JMmgEHSSOIQfIyrgyozJB3XclJXZHtReOmWwx3rLhrMk/ON7Wp/2Fsmz/rakG9pX4KyyfU0DiV7fgsu7GJb2lPYIo3SC+P1Pq+sSZ0nEzZP+GEvX8/79O01sr5XkHmHaM=