language: java
jdk:
- oraclejdk7
before_install:
- chmod +x gradlew
- [sudo] gem install github_changelog_generator
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -i -S
after_success:
  - ./gradlew uploadJars -S
  - ./gradlew curse -i -S
  - ./gradlew createGithubBranches -S
