branches:
  only:
    - /^Development-.*$/
    - /^Minecraft-.*$/
language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- find
- chmod +x gradlew
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
after_success:
  - ./gradlew uploadJars -S
  - ./gradlew curseforge -S
  - ./gradlew createGithubBranches -S

